version: 0.2

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.13.0-beta1/terraform_0.13.0-beta1_linux_386.zip
      - unzip terraform_0.13.0-beta1_linux_386.zip
      - mv terraform /bin
      - rm terraform_0.13.0-beta1_linux_386.zip
  pre_build:
    commands:
      - echo Run Terrafron init
      - cd terraform-code
      - terraform init
      - terraform validate
  build:
    commands:
      - echo Build started on `date`
      - export TF_LOG=TRACE
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo Build completed on `date`
#artifacts:
  #files:
  #  - target/messageUtil-1.0.jar