version: 0.2

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_386.zip
      - unzip terraform_0.12.26_linux_386.zip
      - sudo mv terraform /bin
      - rm terraform_0.12.26_linux_386.zip
      - terraform --help
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      #- mvn install
  post_build:
    commands:
      - echo Build completed on `date`
#artifacts:
  #files:
  #  - target/messageUtil-1.0.jar